<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <NoWarn>$(NoWarn);CA1707;CA1515;CA1861;CA5394;CA2201;CA1062;CA1812;CA1001;CA1822</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SplitVpn.Service\SplitVpn.Service.csproj" />
    <ProjectReference Include="..\..\src\SplitVpn.OpenConnect\SplitVpn.OpenConnect.csproj" />
  </ItemGroup>

</Project>
