<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <UseWPF>true</UseWPF>
    <RootNamespace>SplitVpn.App</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>SplitVpn</AssemblyName>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\*.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="WPF-UI" />
    <PackageReference Include="H.NotifyIcon.Wpf" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Microsoft.Web.WebView2" />
    <PackageReference Include="System.ServiceProcess.ServiceController" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SplitVpn.Core\SplitVpn.Core.csproj" />
  </ItemGroup>

</Project>