<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <!-- Имена тестов с подчёркиваниями и публичные тестовые классы -->
    <NoWarn>$(NoWarn);CA1707;CA1515;CA1861;CA5394;CA2201;CA1062</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SplitVpn.Core\SplitVpn.Core.csproj" />
  </ItemGroup>

</Project>
